name: Test Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  py_version_test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            python -m pip install .
    - name: Run test
      run: |
            python test.py models
            python test.py aliases

  os_test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: "Windows (x64)"
            runner: windows-latest
            architecture: "x64"

          - os: "Windows (x86)"
            runner: windows-latest
            architecture: "x86"

          - os: "MacOS (Apple M)"
            runner: macos-latest

          - os: "MacOS (Intel)"
            runner: macos-13

          - os: "Ubuntu"
            runner: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            python -m pip install .
    - name: Run test
      run: |
            python test.py models
            python test.py aliases
